### PR TITLE
Fix submodule for Travis

### PR DESCRIPTION
**Pull request by entendu**
I think this might do it....

### CODE REVIEW

**Comment by entendu** [comment]
Yep, that did it. :shipit: imo

**Comment by copperwall** [comment]
CR :fire:

**Comment by copperwall** [comment]
Oh wait I didn't even realize this was from a year and a half ago.

**Comment by copperwall** [comment]
Wat you made this before you started working here?

**Comment by djmetzle** [comment]
CR 👍

**Comment by entendu** [comment]
> Wat you made this before you started working here?

haha this and https://github.com/iFixit/alertinator/pull/8 were my coding projects.

**Comment by lexahall** [comment]
QA tips?

**Comment by evannoronha** [comment]
dev_block 🔥 on QA tips

**Comment by entendu** [comment]
This is already merged into #8

**Pull request closed without merging**
